server :
  port : 1939
spring :
  zipkin:
    enabled: true
    service.name: service-a-logging
    sender.type: web
    base-url: http://localhost:9411
    sleuth:
      enabled: true
      sampler:
        probability: 1.0
  application :
    name : service-a-logging
